Async with logs
cyberzac/nn-fe pull request #3
Opened 2018-05-24 14:12 UTC by cyberzac

2018-05-24 21:34 UTC, iamstarkov requested changes

2018-05-24 21:34 UTC, iamstarkov commented on src/components/news-item/index.js
> +        const timeInMs = item.time * 1000;
this should be `NaN` in the first render, could you deploy it?

2018-05-25 07:57 UTC, cyberzac commented on src/components/news-item/index.js
> +        const timeInMs = item.time * 1000;
Yes it will be a NaN, do you want it to render empty when the item is empty?

2018-05-25 08:32 UTC, iamstarkov commented on src/components/news-item/index.js
> +        const timeInMs = item.time * 1000;
@cyberzac yes, I want you to render `<div>Loading…</div>` if you have no data to render

2018-05-25 13:51 UTC, cyberzac commented
Added "Loading ..." in favor of NaN's

2018-05-29 23:50 UTC, iamstarkov approved these changes
LGTM 👍

2018-05-30 10:43 UTC, merged